name: 'Process Secrets for CloudFormation'
description: 'Securely processes CloudFormation parameters with encrypted secrets'
inputs:
  salt-key:
    description: 'Salt key for encrypting/decrypting secrets'
    required: true
  parameter-file:
    description: 'Path to the parameter file'
    required: false
    default: ''
  inline-parameters:
    description: 'JSON string of inline parameters'
    required: false
    default: ''

outputs:
  processed-param-file:
    description: 'Path to the processed parameter file'
    value: ${{ steps.process-parameters.outputs.processed_param_file }}

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install cryptography
    
    - name: Copy Secret Handler Script
      shell: bash
      run: |
        mkdir -p ${{ runner.temp }}/scripts
        cp ${{ github.action_path }}/secret-handler.py ${{ runner.temp }}/scripts/
        chmod +x ${{ runner.temp }}/scripts/secret-handler.py
    
    - name: Encrypt secrets from environment
      id: encrypt-secrets
      shell: bash
      run: |
        echo "Encrypting secrets with salt key..."
        ${{ runner.temp }}/scripts/secret-handler.py encrypt "${{ inputs.salt-key }}"
      
    - name: Process parameters with secrets
      id: process-parameters
      if: inputs.parameter-file != ''
      shell: bash
      run: |
        echo "Processing parameters with encrypted secrets..."
        OUTPUT_FILE="${{ runner.temp }}/processed-parameters.json"
        
        ${{ runner.temp }}/scripts/secret-handler.py process-parameters \
          "${{ steps.encrypt-secrets.outputs.secrets_file }}" \
          "${{ inputs.salt-key }}" \
          "${{ inputs.parameter-file }}" \
          "${OUTPUT_FILE}"
        
        echo "processed_param_file=${OUTPUT_FILE}" >> $GITHUB_OUTPUT
    
    - name: Process inline parameters with secrets
      id: process-inline
      if: inputs.inline-parameters != '' && inputs.inline-parameters != 'null'
      shell: bash
      run: |
        echo "Processing inline parameters with encrypted secrets..."
        TEMP_FILE="${{ runner.temp }}/inline-params.json"
        OUTPUT_FILE="${{ runner.temp }}/processed-inline-params.json"
        
        # Write inline parameters to temp file
        echo '${{ inputs.inline-parameters }}' > "${TEMP_FILE}"
        
        ${{ runner.temp }}/scripts/secret-handler.py process-parameters \
          "${{ steps.encrypt-secrets.outputs.secrets_file }}" \
          "${{ inputs.salt-key }}" \
          "${TEMP_FILE}" \
          "${OUTPUT_FILE}"
        
        echo "processed_inline_file=${OUTPUT_FILE}" >> $GITHUB_OUTPUT
    
    - name: Clean up sensitive files
      if: always()
      shell: bash
      run: |
        echo "Cleaning up sensitive files..."
        rm -f "${{ steps.encrypt-secrets.outputs.secrets_file }}" || true