deployments:
  - resource: a-crs-sns-topic
    environments:
      - dev
    runners:
      dev: ubuntu-latest    
    github_environments:
      dev: CD-EM-CRS-DEV
    aws_regions:
      dev: us-east-1
    aws_secret_names:
      dev: "AWS_ROLE_TO_ASSUME"
    cfn_secret_names:
      dev: "AWS_ROLE_TO_ASSUME"
    parameters:
      dev:
        stack-name: a-crs-ecr-dev
        bucket-name: cd-azdo-central-cfn-a-crs-dev-us-east-2
        target-folder: cloud-formation/rcc/ecr
        source-folder: cloud-formation/rcc/ecr
        filename-patterns: "*.yaml"
        template-name: a-crs-ecr.yaml
        cfnLintEnabled: 'true'
        extraArgs: '--include-checks I --info -i I3013,W2001'
        bucket-upload: "true"
        inline-parameters:
          - ParameterKey: ECRName
            ParameterValue: a-crs-ecr-dev
        tags: Name=a-crs-s3-bucket-dev-twt123


        

