deployments:
  - resource: a-crs-sns-topic
    environments:
      - dev
    runners:
      dev: ubuntu-latest    
    github_environments:
      dev: CD-EM-CRS-DEV
    aws_regions:
      dev: us-east-1
    aws_roles:
      dev:
        aws_role_to_assume: AWS_CRS_ROLE_TO_ASSUME
        cfn_role_arn: CFN_ROLE_ARN
        iam_execution_role_arn: AWS_CRS_ROLE_TO_ASSUME
    parameters:
      dev:
        stack-name: a-crs-ecr-dev
        bucket-name: cd-azdo-central-cfn-a-crs-dev-us-east-2
        target-folder: cloud-formation/rcc/ecr
        source-folder: cloud-formation/rcc/ecr
        filename-patterns: "*.yaml"
        template-name: a-crs-ecr.yaml
        cfnLintEnabled: 'true'
        extraArgs: '--include-checks I --info -i I3013,W2001'
        bucket-upload: "true"
        inline-parameters:
          - ParameterKey: ECRName
            ParameterValue: a-crs-ecr-dev
        tags: Name=a-crs-s3-bucket-dev-twt-test-123-test-test


        

