name: 'Detect Changed Applications'
description: 'Detects changes in application deployment configurations'
inputs:
  github_token:
    description: 'GitHub token for API access'
    required: true
  event_name:
    description: 'GitHub event name'
    required: true
  github_sha:
    description: 'The commit SHA that triggered the workflow'
    required: true
  github_ref:
    description: 'The branch or tag ref that triggered the workflow'
    required: true
  event_before:
    description: 'The SHA of the previous commit in a push event'
    required: false
    default: ''
  pull_request_number:
    description: 'Pull request number for PR events'
    required: false
    default: ''
  resource_path_input:
    description: 'Resource path provided via workflow_dispatch'
    required: false
    default: ''
  repository:
    description: 'GitHub repository'
    required: true
  app_name:
    description: 'Application name for path validation in workflow_dispatch events'
    required: false
    default: ''

outputs:
  paths:
    description: 'Comma-separated list of detected resource paths'
    value: ${{ steps.detect-applications.outputs.paths }}

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Detect Changed Applications
      id: detect-applications
      shell: bash
      run: |
        # Function to log messages with a timestamp
        log() {
          echo "$(date '+%Y-%m-%d %H:%M:%S') - $1"
        }
        
        # For workflow_dispatch events
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          # Get the resource path and app name
          RESOURCE_PATH="${{ github.event.inputs.resource_path }}"
          APP_NAME="${{ inputs.app_name }}"
          
          # Validate resource path against app_name if app_name is provided
          if [[ -n "$APP_NAME" ]]; then
            # Check if the resource path starts with cloud-formation/{app_name}/
            EXPECTED_PREFIX="cloud-formation/$APP_NAME/"
            
            if [[ "$RESOURCE_PATH" != $EXPECTED_PREFIX* ]]; then
              echo "ERROR: Resource path '$RESOURCE_PATH' is not valid for app '$APP_NAME'"
              echo "Resource path must start with '$EXPECTED_PREFIX'"
              echo "paths=" >> $GITHUB_OUTPUT
              exit 0
            fi
          fi
          
          echo "paths=$RESOURCE_PATH" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        CHANGED_PATHS=()
        CHANGED_FILES=""
        
        # Determine event type and get changed files
        EVENT_NAME="${{ github.event_name }}"
        
        if [[ "$EVENT_NAME" == "pull_request" ]]; then
          PR_NUMBER="${{ github.event.pull_request.number }}"
          
          # Get only the latest commit SHA in the PR
          HEAD_SHA="${{ github.event.pull_request.head.sha }}"
          # Get the SHA of the commit before the latest one
          PREV_SHA=$(git rev-parse $HEAD_SHA^)
          
          # Get changes from just the latest commit, not the entire PR
          CHANGED_FILES=$(git diff --name-only $PREV_SHA $HEAD_SHA)
          
          # If no files were found, fall back to the GitHub API
          if [[ -z "$CHANGED_FILES" ]]; then
            # Save the API response for inspection
            API_RESPONSE=$(curl -s -H "Authorization: token ${{ github.token }}" \
              "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/files")
            
            # Check if we got a valid JSON array before processing
            if echo "$API_RESPONSE" | jq 'if type=="array" then true else false end' | grep -q true; then
              CHANGED_FILES=$(echo "$API_RESPONSE" | jq -r '.[].filename')
            else
              # Fallback to git diff as a recovery mechanism
              CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD || echo "")
            fi
          fi
          
        elif [[ "$EVENT_NAME" == "push" ]]; then
          PARENT_COUNT=$(git cat-file -p ${{ github.sha }} | grep -c "^parent ")
          
          if [[ $PARENT_COUNT -gt 1 ]]; then
            MERGE_BASE=$(git merge-base ${{ github.event.before }} ${{ github.sha }})
            CHANGED_FILES=$(git diff --name-only $MERGE_BASE ${{ github.sha }})
          else
            CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
            
            if [[ -z "$CHANGED_FILES" ]]; then
              CHANGED_FILES=$(git diff --name-only ${{ github.event.before }}..${{ github.sha }})
            fi
          fi
        else
          CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD || echo "")
        fi
        
        while IFS= read -r file; do
          # Skip empty lines
          if [[ -z "$file" ]]; then
            continue
          fi
        
          # Check if the file is a deployment config file
          if [[ "$file" == cloud-formation/*/*.y*ml ]]; then
            RESOURCE_PATH=$(dirname "$file")
        
            if [[ ! " ${CHANGED_PATHS[@]} " =~ " ${RESOURCE_PATH} " ]]; then
              CHANGED_PATHS+=("$RESOURCE_PATH")
            fi
          fi
        done <<< "$CHANGED_FILES"
        
        # Convert array to comma-separated string
        if [[ ${#CHANGED_PATHS[@]} -gt 0 ]]; then
          IFS=,
          PATHS="${CHANGED_PATHS[*]}"
        else
          PATHS=""
        fi
        
        echo "paths=$PATHS" >> $GITHUB_OUTPUT
        
        # Debug info for empty results
        if [[ -z "$PATHS" ]]; then
          log "No paths detected. Debug information:"
          log "Event name: $EVENT_NAME"
          log "Ref: ${{ github.ref }}"
          log "Base ref: ${{ github.event.pull_request.base.ref || 'N/A' }}"
          log "SHA: ${{ github.sha }}"
          log "Before: ${{ github.event.before || 'N/A' }}"
          log "After: ${{ github.event.after || 'N/A' }}"
        fi
