name: 'Detect Changed Applications'
description: 'Detects changes in application deployment configurations'
inputs:
  github_token:
    description: 'GitHub token for API access'
    required: true
  event_name:
    description: 'GitHub event name'
    required: true
  github_sha:
    description: 'The commit SHA that triggered the workflow'
    required: true
  github_ref:
    description: 'The branch or tag ref that triggered the workflow'
    required: true
  event_before:
    description: 'The SHA of the previous commit in a push event'
    required: false
    default: ''
  pull_request_number:
    description: 'Pull request number for PR events'
    required: false
    default: ''
  resource_path_input:
    description: 'Resource path provided via workflow_dispatch'
    required: false
    default: ''
  repository:
    description: 'GitHub repository'
    required: true
  app_name:
    description: 'Application name for path validation in workflow_dispatch events'
    required: false
    default: ''

outputs:
  paths:
    description: 'Comma-separated list of detected resource paths'
    value: ${{ steps.detect-applications.outputs.paths }}

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Detect Changed Applications
      id: detect-applications
      shell: bash
      run: python ./.github/actions/detect-changed-applications/detect_changed_applications.py
      env:
        INPUT_EVENT_NAME: ${{ inputs.event_name }}
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_GITHUB_SHA: ${{ inputs.github_sha }}
        INPUT_GITHUB_REF: ${{ inputs.github_ref }}
        INPUT_EVENT_BEFORE: ${{ inputs.event_before }}
        INPUT_REPOSITORY: ${{ inputs.repository }}
        INPUT_APP_NAME: ${{ inputs.app_name }}
        INPUT_PULL_REQUEST_NUMBER: ${{ inputs.pull_request_number }}
        INPUT_RESOURCE_PATH_INPUT: ${{ inputs.resource_path_input }}
        GITHUB_EVENT_PATH: ${{ github.event_path }}