deployments:
  - environments:
      - dev
      - int
      - prod
      - stg
      - int-dr
    runners:
      dev: custom
      int: custom
      prod: custom
      stg: custom
      int-dr: custom
    github_environments:
      dev: Development
      int: Integration
      prod: Production
      stg: Staging
      int-dr: IntDR
    aws_regions:
      dev: us-east-1
      int: us-east-1
      prod: us-east-1
      stg: us-east-1
      int-dr: us-west-2
    aws_role_secrets:
      dev: AWS_ROLE_TO_ASSUME
      int: AWS_ROLE_TO_ASSUME
      prod: AWS_ROLE_TO_ASSUME
      stg: AWS_ROLE_TO_ASSUME
      int-dr: AWS_ROLE_TO_ASSUME
    cfn_role_secrets:
      dev: CFN_ROLE_ARN
      int: CFN_ROLE_ARN
      prod: CFN_ROLE_ARN
      stg: CFN_ROLE_ARN
      int-dr: CFN_ROLE_ARN
    iam_execution_role_secrets:
      dev: IAM_EXECUTION_ROLE_ARN
      int: IAM_EXECUTION_ROLE_ARN
      prod: IAM_EXECUTION_ROLE_ARN
      stg: IAM_EXECUTION_ROLE_ARN
      int-dr: IAM_EXECUTION_ROLE_ARN
    parameters:
      dev:
        stack-name: "dev-app-stack"
        bucket-name: "dev-app-bucket"
        bucket-upload: "true"
        target-folder: "dev"
        source-folder: "src"
        template-name: "template.yaml"
        filename-patterns: "*.yaml"
        cfnLintEnabled: "true"
        tags: Name=nazar-stack-dev
        extraArgs: "--capabilities CAPABILITY_IAM"
        parameter-file: "parameters/dev.json"
        inline-parameters:
          Environment: "dev"
          Stage: "development"
        tags: "Environment=dev,Project=MyApp"
      int:
        stack-name: "int-app-stack"
        bucket-name: "int-app-bucket"
        bucket-upload: "true"
        target-folder: "int"
        source-folder: "src"
        template-name: "template.yaml"
        filename-patterns: "*.yaml"
        cfnLintEnabled: "true"
        extraArgs: "--capabilities CAPABILITY_IAM"
        parameter-file: "parameters/int.json"
        inline-parameters:
          Environment: "int"
          Stage: "integration"
        tags: "Environment=int,Project=MyApp"
      prod:
        stack-name: "prod-app-stack"
        bucket-name: "prod-app-bucket"
        bucket-upload: "true"
        target-folder: "prod"
        source-folder: "src"
        template-name: "template.yaml"
        filename-patterns: "*.yaml"
        cfnLintEnabled: "true"
        extraArgs: "--capabilities CAPABILITY_IAM"
        parameter-file: "parameters/prod.json"
        inline-parameters:
          Environment: "prod"
          Stage: "production"
        tags: "Environment=prod,Project=MyApp"
      stg: 
        dependsOn: deploy-int
        stack-name: "stg-app-stack"
        bucket-name: "stg-app-bucket"
        bucket-upload: "true"
        target-folder: "stg"
        source-folder: "src"
        template-name: "template.yaml"
        filename-patterns: "*.yaml"
        cfnLintEnabled: "true"
        extraArgs: "--capabilities CAPABILITY_IAM"
        parameter-file: "parameters/stg.json"
        inline-parameters:
          Environment: "stg"
          Stage: "staging"
        tags: "Environment=stg,Project=MyApp"
        custom_deployment: "true"