deployments:
  - resource: a-crs-ecc-sns
    environments:
      - dev
      - int
    runners:
      dev: custom
      int: custom
    github_environments:
      dev: CD-EM-CRS-DEV
      int: CD-EM-CRS-INT
    aws_regions:
      dev: us-east-1
      int: us-east-1
    aws_role_secrets:
      dev: AWS_ROLE_TO_ASSUME
      int: AWS_ROLE_TO_ASSUME
    cfn_role_secrets:
      dev: CFN_ROLE_ARN
      int: CFN_ROLE_ARN
    iam_execution_role_secrets:
      dev: IAM_EXECUTION_ROLE_ARN
      int: IAM_EXECUTION_ROLE_ARN
    github_vars:
      dev:
        tags: A_CRS_TAGS
      int: 
        tags: A_CRS_TAGS  
    parameters:
      dev:
        stack-name: 'a-crs-sns-dev-test-24'
        bucket-name: 'nzrb-home-test'
        bucket-upload: 'true'
        target-folder: cloud-formation/rcc/sns-topic-34
        source-folder: cloud-formation/rcc/sns-topic-34
        # filename-patterns: "*.yaml"
        template-name: 'template.yaml'
        inline-parameters:
          - ParameterKey: email
            ParameterValue: vezarqrchik@gmail.com
          