deployments:
  - resource: a-crs-ecc-sns
    environments:
      - dev
    runners:
      dev: ubuntu-latest    
    github_environments:
      dev: CD-EM-CRS-DEV
    aws_regions:
      dev: us-east-2
    aws_role_secrets:
      dev: AWS_CRS_ROLE_TO_ASSUME
    cfn_role_secrets:
      dev: CFN_ROLE_ARN
    iam_execution_role_secrets:
      dev: IAM_EXECUTION_ROLE_ARN
    github_vars:
      dev:
        tags: A_CRS_TAGS
    parameters:
      dev:
        stack-name: 'a-crs-sns-dev-test'
        bucket-name: 'nzrb-home-test'
        bucket-upload: 'true'
        target-folder: cloud-formation/rcc/a-crs-sns
        source-folder: cloud-formation/rcc/a-crs-sns
        filename-patterns: "*.yaml"
        template-name: 'a-crs-sns.yaml'
        cfnLintEnabled: 'true'
        extraArgs: '--include-checks I --info -i I3013,W2001'
        inline-parameters:
          - ParameterKey: TopicName
            ParameterValue: a-crs-CloudWatch-Alarms-dev-test
          - ParameterKey: email
            ParameterValue: "${{ secrets.NZRB }}"