deployments:
  - resource: a-crs-ecc-sns
    environments:
      - dev
    runners:
      dev: custom
    github_environments:
      dev: CD-EM-CRS-DEV
    aws_regions:
      dev: us-east-1
    aws_role_secrets:
      dev: AWS_ROLE_TO_ASSUME
    cfn_role_secrets:
      dev: CFN_ROLE_ARN
    iam_execution_role_secrets:
      dev: IAM_EXECUTION_ROLE_ARN
    github_vars:
      dev:
        tags: A_CRS_TAGS
    parameters:
      dev:
        stack-name: 'a-crs-sns-dev-test'
        bucket-name: 'nzrb-home-test'
        bucket-upload: 'true'
        target-folder: cloud-formation/rcc/sns-topic-34
        source-folder: cloud-formation/rcc/sns-topic-34
        # filename-patterns: "*.yaml"
        template-name: 'template.yaml'
        inline-parameters:
          - ParameterKey: TopicName
            ParameterValue: a-crs-CloudWatch-Alarms-dev-test
        parameter-file: cloud-formation/rcc/sns-topic-34/dev.json  

            