name: 'Generate Combined Deployment Matrices'
description: 'Parses multiple deployment config files and generates combined matrices'
inputs:
  resource_paths:
    description: 'Comma-separated paths to resources (e.g., cloud-formation/rcc/a-crs-spa,cloud-formation/rcc/another-resource)'
    required: true
  specific_environment:
    description: 'Specific environment to deploy (empty for all configured)'
    required: false
    default: ''

outputs:
  dev_matrix:
    description: 'Matrix for DEV deployments'
    value: ${{ steps.generate-matrices.outputs.dev_matrix }}
  int_matrix:
    description: 'Matrix for INT deployments'
    value: ${{ steps.generate-matrices.outputs.int_matrix }}
  prod_matrix:
    description: 'Matrix for PROD deployments'
    value: ${{ steps.generate-matrices.outputs.prod_matrix }}
  custom_matrix:
    description: 'Matrix for custom deployments (stg, int-dr, etc)'
    value: ${{ steps.generate-matrices.outputs.custom_matrix }}
  custom_deployment_after:
    description: 'When to run custom deployments (dev, int, prod)'
    value: ${{ steps.generate-matrices.outputs.custom_deployment_after }}
runs:
  using: "composite"
  steps:
    - name: Install yq
      shell: bash
      run: |
        if ! command -v yq &> /dev/null; then
          echo "Installing yq..."
          VERSION=v4.30.8
          BINARY=yq_linux_amd64
          wget https://github.com/mikefarah/yq/releases/download/${VERSION}/${BINARY}.tar.gz -O - | \
            tar xz
          chmod +x ${BINARY}
          sudo mv ${BINARY} /usr/bin/yq || mkdir -p $HOME/bin && mv ${BINARY} $HOME/bin/yq && echo "$HOME/bin" >> $GITHUB_PATH
        fi

    - name: Generate deployment matrices
      id: generate-matrices
      shell: bash
      run: python ./.github/actions/combined-matrix-generator/generate_deployment_matrices.py
      env:
        INPUT_RESOURCE_PATHS: ${{ inputs.resource_paths }}
        INPUT_SPECIFIC_ENVIRONMENT: ${{ inputs.specific_environment }}