name: 'Generate Combined Deployment Matrices'
description: 'Parses multiple deployment config files and generates combined matrices'
inputs:
  resource_paths:
    description: 'Comma-separated paths to resources (e.g., cloud-formation/rcc/a-crs-spa,cloud-formation/rcc/another-resource)'
    required: true
  specific_environment:
    description: 'Specific environment to deploy (empty for all configured)'
    required: false
    default: ''

outputs:
  dev_matrix:
    description: 'Matrix for DEV deployments'
    value: ${{ steps.generate-matrices.outputs.dev_matrix }}
  int_matrix:
    description: 'Matrix for INT deployments'
    value: ${{ steps.generate-matrices.outputs.int_matrix }}
  prod_matrix:
    description: 'Matrix for PROD deployments'
    value: ${{ steps.generate-matrices.outputs.prod_matrix }}
  custom_matrix:
    description: 'Matrix for custom deployments (stg, int-dr, etc)'
    value: ${{ steps.generate-matrices.outputs.custom_matrix }}
  custom_deployment_after:
    description: 'When to run custom deployments (dev, int, prod)'
    value: ${{ steps.generate-matrices.outputs.custom_deployment_after }}
runs:
  using: "composite"
  steps:
    - name: Generate deployment matrices
      id: generate-matrices
      shell: bash
      run: | 
        pip install PyYAML
        python ./.github/actions/Scripts/main.py matrix_generator
      env:
        INPUT_RESOURCE_PATHS: ${{ inputs.resource_paths }}
        INPUT_SPECIFIC_ENVIRONMENT: ${{ inputs.specific_environment }}